In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
              [4,5,6]],
             [[7,8,9],
             [10,11,12]]])

In [3]:
a3.ndim

3

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1, a1.ndim, a1.dtype, a1.size, a1.shape

(array([1, 2, 3, 4, 5]), 1, dtype('int32'), 5, (5,))

In [5]:
# Attributes of 2-dimensional array
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Attributes of 3-dimensional array
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros(shape=(7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10, size=(7,2))

array([[4, 0],
       [5, 5],
       [2, 4],
       [3, 9],
       [8, 4],
       [3, 8],
       [0, 9]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.65028861, 0.86322576, 0.77504236, 0.62276202, 0.37323006],
       [0.36891491, 0.79292325, 0.74376354, 0.42434324, 0.83837447],
       [0.87232062, 0.18975839, 0.86517366, 0.07438298, 0.01777149]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size = (4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(1, 10, size=(3,7))

# Find the unique numbers in the array you just created
array, np.unique(array)

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 array([1, 2, 3, 4, 5, 7, 9]))

In [15]:
# Find the 0'th index of the latest array you created
array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [16]:
# Get the first 2 rows of latest array you created
array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2, :2]

array([[9, 1],
       [5, 3]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4 = np.random.randint(10, size=(3,5))
ones = np.ones((3,5))

In [19]:
# Add the two arrays together
a4 +ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [20]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))

In [21]:
# Try add the array of ones and the other most recent array together
ones+ a4

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

It show the error because size of the two array is differrent so we can't perform the action.

In [22]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))

In [23]:
# Subtract the new array of ones from the other most recent array
a4 - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [24]:
# Multiply the ones array with the latest array
a4 * ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [25]:
# Take the latest array to the power of 2 using '**'
a4 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [26]:
# Do the same thing with np.square()
np.square(a4)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [27]:
# Find the mean of the latest array using np.mean()
a4.mean()

3.8666666666666667

In [28]:
# Find the maximum of the latest array using np.max()
a4.max()

9

In [29]:
# Find the minimum of the latest array using np.min()
a4.min()

0

In [30]:
# Find the standard deviation of the latest array
a4.std()

2.578543947441829

In [31]:
# Find the variance of the latest array
a4.var()

6.648888888888889

In [32]:
a4

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [33]:
# Reshape the latest array to (3, 5, 1)
a4.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [34]:
# Transpose the latest array
a4.transpose()

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [35]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(10, size = (3,3))
mat2 = np.random.randint(10, size = (3,2))

In [36]:
mat1

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4]])

In [37]:
mat2

array([[1, 4],
       [7, 9],
       [8, 8]])

In [38]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1,mat2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [39]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3 = np.random.randint(10, size = (4,3))

mat4 = np.random.randint(10, size = (4,3))

In [40]:
mat3

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2],
       [0, 7, 2]])

In [41]:
mat4

array([[2, 0, 4],
       [9, 6, 9],
       [8, 6, 8],
       [7, 1, 0]])

In [42]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3, mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [43]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(mat3.T,mat4)

array([[128,  90, 128],
       [184,  91, 151],
       [ 42,  14,  40]])

In [44]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
mat5 = np.random.randint(10, size = (4,3))
mat6 = np.random.randint(10, size = (4,3))

In [45]:
# Compare the two arrays with '>'
mat5 > mat6

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [46]:
# Compare the two arrays with '>='
mat5 >= mat6

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [47]:
# Find which elements of the first array are greater than 7
mat5>7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [48]:
# Which parts of each array are equal? (try using '==')
mat5 == mat6

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [58]:
# Sort one of the arrays you just created in ascending order
np.sort(mat5)

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5],
       [2, 2, 4]])

In [59]:
# Sort the indexes of one of the arrays you just created
np.argsort(mat5)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [60]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(mat5)

2

In [61]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat5)

6

In [64]:
mat5

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5],
       [2, 2, 4]])

In [66]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(mat6, axis=1)

array([2, 2, 0, 0], dtype=int64)

In [67]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(mat6, axis=0)

array([0, 3, 2], dtype=int64)

In [68]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 1.79428084,  0.58068954,  0.29765045, -1.02811577, -1.41859646],
       [ 0.19033698,  0.13575383,  0.60808966,  0.70498131,  0.36092338],
       [-1.46696789,  0.89262947, -0.10525713, -0.95534644, -0.41476463]])

In [70]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced = np.linspace(1,100,10)

In [71]:
evenly_spaced

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])