# Dot product using numpy array for matrices.

In [17]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh =[102, 43, 37]
unova = [69, 96, 70]

In [19]:
weight= [0.3, 0.2, 0.5]

In [20]:
import numpy as np

In [36]:
region=np.array([[73,67,43],
                 [73, 67, 43],
                 [91, 88, 64],
                 [87, 134, 58],
                 [102, 43, 37],
                 [69, 96, 70]])

In [37]:
print(region)

[[ 73  67  43]
 [ 73  67  43]
 [ 91  88  64]
 [ 87 134  58]
 [102  43  37]
 [ 69  96  70]]


In [38]:
weight=np.array([0.3,0.2,0.5])

In [39]:
print(weight)

[0.3 0.2 0.5]


## Multiplication operation in matrices

In [40]:
prediction=np.dot(region,weight)

In [42]:
print(prediction)

[56.8 56.8 76.9 81.9 57.7 74.9]


In [43]:
region*weight

array([[21.9, 13.4, 21.5],
       [21.9, 13.4, 21.5],
       [27.3, 17.6, 32. ],
       [26.1, 26.8, 29. ],
       [30.6,  8.6, 18.5],
       [20.7, 19.2, 35. ]])

In [47]:
(kanto*weight).sum()

56.8

In [49]:
region @ weight

array([56.8, 56.8, 76.9, 81.9, 57.7, 74.9])

In [50]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [51]:
a @ b

70

In [52]:
b.sum()

26

In [53]:
a.sum()

10

NOTE: 
1. np.dot() atrixand @ perform the same operation called Matrix multiplication.
2. sum() function return sum of numbers in a array.

## Creating 2D and 3D Matrices

In [56]:
region=np.array([[73,67,43],
                 [73, 67, 43],
                 [91, 88, 64],
                 [87, 134, 58],
                 [102, 43, 37],
                 [69, 96, 70]])

In [57]:
region.shape

(6, 3)

In [2]:
import numpy as np

In [8]:
arr1=np.array([
    [[1,2,3],
     [4,5,6]],
    [[10,11,12],
     [13,14,15]]])

In [9]:
arr1.shape

(2, 2, 3)

We can't create the differert set for 3D if we create it error occurs

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.dtype

dtype('int64')

## Working with CSV(Coma -Seperated Values) files

we are processing the data of 10000 data of Temperature, Rainfall ,Humidity

In [23]:
import urllib.request
urllib.request.urlretrieve(
'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv',
'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fdf786325e0>)

In [25]:
climate_data=np.genfromtxt('climate.txt', delimiter=',',skip_header=1)

In [27]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [28]:
climate_data.shape

(10000, 3)

In [30]:
weight=np.array([0.3,0.2,0.5])

In [31]:
weight

array([0.3, 0.2, 0.5])

In [33]:
yeild=climate_data @ weight

In [34]:
yeild

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [36]:
yeild.shape

(10000,)

we are just adding the yeild result in last colum in the matrix by using concatenate

axis=1 add the column value
reshape to (1000,1) because concatenate does not shape of yeild(1000,)

In [50]:
Climate_results=np.concatenate((climate_data,yeild.reshape(10000,1)),axis=1)

In [51]:
Climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [67]:
np.savetxt('climate result.txt',
          Climate_results,
          fmt='%.2f',
          delimiter=',',
          header='temperature,rainfall,humidity,yeild of crop',
          comments='')

We can just give space in file by using delimiter but originaly of csv file not i am goingto change

## Arithmetic operation and comparision in numpy(Matrices)

In [2]:
import numpy as np

In [4]:
arr1=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [5]:
arr2=np.array([
    [13,14,15,16],
    [17,18,19,20],
    [21,22,23,24]])

In [6]:
arr1+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
arr1-3

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [8]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr1*3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [10]:
arr1+arr2

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [11]:
arr1-arr2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [12]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [14]:
arr1%2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [16]:
arr2%5

array([[3, 4, 0, 1],
       [2, 3, 4, 0],
       [1, 2, 3, 4]])

In [17]:
arr1==arr2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [18]:
arr1!=arr2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
arr1<=arr2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr1.sum()

78

# Broadcasting

In [22]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr3=np.array([[1,2,3,4],
               [5,6,7,8]])

In [30]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr1+arr3

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

we can usually broadcast(which replicate the copy without making actual copy)

In [37]:
arr4=np.array([1,2,3,4])

In [44]:
arr3+arr4

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [45]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
arr5=([1])

In [43]:
arr3+arr5

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

# Indexing and slicing

In [48]:
arr3d=np.array([
    [[1,2,3],
    [4,5,6]],
    [[7,8,9],
    [10,11,12]]
])

In [49]:
arr3d.shape

(2, 2, 3)

In [54]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr3d[0,1]

array([4, 5, 6])

In [56]:
arr3d[0,1,2]

6

In [57]:
arr3d[1:]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[:0]

array([], shape=(0, 2, 3), dtype=int64)

In [59]:
arr3d[:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [61]:
arr3d[:1,0]

array([[1, 2, 3]])

Some other mode of creating numpy array

In [64]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [71]:
np.random.rand(3,4)

array([[0.37779462, 0.74195045, 0.84251382, 0.7834944 ],
       [0.69354689, 0.70324342, 0.15127994, 0.60325171],
       [0.02296888, 0.43311609, 0.94531797, 0.04418909]])

In [70]:
np.random.randn(3,5)

array([[-0.75744374, -0.8007626 , -0.88673832,  0.07079243, -0.93306271],
       [ 0.86293556, -0.59397764, -1.09359026,  0.65722454,  0.07057631],
       [-0.77387561, -0.30518784,  1.06619267,  0.16844739, -0.49950174]])

In [72]:
np.full((3,4),12)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [75]:
np.arange(0,100,7)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [83]:
np.linspace(3,4,3)

array([3. , 3.5, 4. ])

# Numpy function for data science

Median is middle value of sorted array or list
if even :
    median=(n-1)/2
else:
    aaverge of two middle value 

In [ ]:
Median,mean

In [92]:
b=np.full((4,4,4),7)

In [93]:
b

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [99]:
np.median(b,axis=2)

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [100]:
np.median(b)

7.0

In [109]:
c=np.eye(4)

In [117]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [118]:
np.mean(c)

0.25

Mode operation we can learn in scipy

## Standard deviation

In [119]:
a=[12,1,3,5,6,7,98,45,98]

In [120]:
np.std(a)

38.1433294331645

## Variance

In [124]:
a

[12, 1, 3, 5, 6, 7, 98, 45, 98]

In [125]:
np.var(a)

1454.9135802469134

## Percentile

In [126]:
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

In [128]:
np.percentile(ages,75)

43.0

43 people younger or equal to age 43

In [132]:
np.percentile(ages,90)

61.0

90 people younger or equal to age 90